// Shared helpers for the Style Dictionary build: mode expansion (Dimensions collection
// carries {mobile, web} pairs, not a single `value`) and CSS value formatting.
// Kept out of build.mjs so build.mjs reads as orchestration.

export function expandMode(node, mode) {
  if (node && typeof node === 'object' && !Array.isArray(node)) {
    if ('mobile' in node && 'web' in node) {
      const { mobile, web, ...rest } = node;
      return { value: node[mode], ...rest };
    }
    const out = {};
    for (const key of Object.keys(node)) out[key] = expandMode(node[key], mode);
    return out;
  }
  return node;
}

export function cssValue(token) {
  switch (token.type) {
    case 'color':
      return token.value;
    case 'fontFamily':
      return `"${token.value}"`;
    case 'fontWeight':
      return String(token.value);
    case 'dimension':
      return `${token.value}px`;
    default:
      return String(token.value);
  }
}

export const GENERATED_BANNER_CSS = `/**
 * AUTO-GENERATED by Style Dictionary from tokens/primitives.json, tokens/color.json, tokens/dimensions.json.
 * Do not edit this file directly — edit variables in Figma, run \`npm run sync-figma\`, then \`npm run tokens:build\`.
 */
`;
