// Shared helpers for the Style Dictionary build: mode expansion (Dimensions collection
// carries {mobile, web} pairs, not a single `value`), Dart identifier casing, and the
// custom CSS/Dart format bodies. Kept out of build.mjs so build.mjs reads as orchestration.

export function expandMode(node, mode) {
  if (node && typeof node === 'object' && !Array.isArray(node)) {
    if ('mobile' in node && 'web' in node) {
      const { mobile, web, ...rest } = node;
      return { value: node[mode], ...rest };
    }
    const out = {};
    for (const key of Object.keys(node)) out[key] = expandMode(node[key], mode);
    return out;
  }
  return node;
}

// "link-hover" -> "linkHover", "50" -> "50" (kept as-is, prefixed by caller when needed)
export function toCamel(...parts) {
  return parts
    .join('-')
    .split('-')
    .map((word, i) => (i === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1)))
    .join('');
}

export function dartFieldName(pathParts) {
  // pathParts e.g. ['color','primitive','ocean','50'] or ['color','text','primary']
  const meaningful = pathParts.filter((p) => p !== 'color' && p !== 'primitive' && p !== 'semantic');
  return toCamel(...meaningful);
}

export function cssValue(token) {
  switch (token.type) {
    case 'color':
      return token.value;
    case 'fontFamily':
      return `"${token.value}"`;
    case 'fontWeight':
      return String(token.value);
    case 'dimension':
      return `${token.value}px`;
    default:
      return String(token.value);
  }
}

function hex2(n) {
  return Math.round(n).toString(16).padStart(2, '0').toUpperCase();
}

export function dartColorLiteral(hexOrRgba) {
  if (hexOrRgba.startsWith('rgba')) {
    const [r, g, b, a] = hexOrRgba
      .replace(/rgba?\(|\)/g, '')
      .split(',')
      .map((n) => parseFloat(n));
    return `Color(0x${hex2(a * 255)}${hex2(r)}${hex2(g)}${hex2(b)})`;
  }
  const hex = hexOrRgba.replace('#', '').toUpperCase();
  const rgb = hex.length === 8 ? hex.slice(0, 6) : hex;
  const alpha = hex.length === 8 ? hex.slice(6, 8) : 'FF';
  return `Color(0x${alpha}${rgb})`;
}

export function dartDoc(description) {
  if (!description) return '';
  const escaped = description.replace(/\*\//g, '*\\/');
  return `  /// ${escaped}\n`;
}

export const GENERATED_BANNER_CSS = `/**
 * AUTO-GENERATED by Style Dictionary from tokens/primitives.json, tokens/color.json, tokens/dimensions.json.
 * Do not edit this file directly — edit variables in Figma, run \`npm run sync-figma\`, then \`npm run tokens:build\`.
 */
`;

export const GENERATED_BANNER_DART = `// AUTO-GENERATED by Style Dictionary from tokens/primitives.json, tokens/color.json, tokens/dimensions.json.
// Do not edit this file directly — edit variables in Figma, run \`npm run sync-figma\`, then \`npm run tokens:build\`.
// Dimension values below use the Mobile mode from the Dimensions collection (this file feeds the Flutter client).
`;
